### ISSUE TITLE
compilation failed CMake v3.31.1 or v3.18.

### ISSUE THREAD

**Issue by stephane-couget** [Tienisto/rhttp#45]
observation,  while compiling 

```
  +60 ms] Building Linux application...
[   +6 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/scotty/AndroidStudioProjects/rhttp2s/linux
[ +172 ms] -- The CXX compiler identification is Clang 18.1.8
[   +5 ms] -- Detecting CXX compiler ABI info
[ +137 ms] -- Detecting CXX compiler ABI info - done
[  +14 ms] -- Check for working CXX compiler: /usr/bin/clang++ - skipped
[        ] -- Detecting CXX compile features
[        ] -- Detecting CXX compile features - done
[  +28 ms] -- Found PkgConfig: /usr/bin/pkg-config (found version "2.3.0")
[        ] -- Checking for module 'gtk+-3.0'
[  +10 ms] --   Found gtk+-3.0, version 3.24.43
[  +92 ms] -- Checking for module 'glib-2.0'
[  +10 ms] --   Found glib-2.0, version 2.82.4
[  +28 ms] -- Checking for module 'gio-2.0'
[  +12 ms] --   Found gio-2.0, version 2.82.4
```
And I get this

```
[  +42 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/rhttp/cargokit/cmake/cargokit.cmake:87 (target_link_libraries):
[   +2 ms]   Attempt to add link library
[        ]   "/home/scotty/AndroidStudioProjects/rhttp2s/build/linux/x64/release/plugins/rhttp/librhttp2s.so"
[        ]   to target "rhttp2s" which is not built in this directory.
[        ]   This is allowed only when policy CMP0079 is set to NEW.
[        ] Call Stack (most recent call first):
[        ]   flutter/ephemeral/.plugin_symlinks/rhttp/linux/CMakeLists.txt:11 (apply_cargokit)
[        ] -- Configuring incomplete, errors occurred!
[  +20 ms] Building Linux application... (completed in 575ms)
[        ] "flutter linux" took 2 324ms.
[   +5 ms] Unable to generate build files
```

with
```
name: rhttp2s
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dio_compatibility_layer: ^0.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  rhttp: ^0.9.8
  flutter_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on Manjaro Linux 6.12.4-1-MANJARO, locale fr_FR.utf8)
    • Flutter version 3.27.1 on channel stable at /home/scotty/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (il y a 2 jours), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/scotty/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/scotty/tools/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.31.2
    • ninja version 1.12.1
    • pkg-config version 2.3.0

[✓] Android Studio (version 2024.2)
    • Android Studio at /home/scotty/tools/android-studio
    • Flutter plugin version 83.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.12.4-1-MANJARO

[✓] Network resources
    • All expected network resources are available.
```

any idea? 

Kind regards,
